# Numpy 

In [2]:
import numpy as np


In [3]:
np.__version__

'2.3.5'

# Creating Arrays

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [7]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3.0)

array([0., 1., 2.])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(20,10)

array([], dtype=int64)

In [13]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [14]:
np.zeros(3) #1d array (parameter tunning)

array([0., 0., 0.])

In [15]:
np.zeros(3, dtype=int) #1d array (hyperparameter tunning)

array([0, 0, 0])

In [16]:
np.zeros([2,2]) #2d array

array([[0., 0.],
       [0., 0.]])

In [17]:
np.zeros([10,10], dtype=int) #nd array (no of rows and col)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [18]:
np.ones(4)

array([1., 1., 1., 1.])

In [19]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [20]:
range(5)

range(0, 5)

In [21]:
r = range(5)
r

range(0, 5)

In [22]:
for i in r:
    print(i)

0
1
2
3
4


In [23]:
list(range(5))

[0, 1, 2, 3, 4]

In [24]:
range(1,10)

range(1, 10)

In [25]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
list(range(1,10,3))

[1, 4, 7]

In [27]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [28]:
np.random.rand(3)

array([0.81522596, 0.12254008, 0.71243755])

In [29]:
np.random.rand(3)

array([0.93190152, 0.0976978 , 0.10621816])

In [30]:
np.random.rand(3,4)

array([[0.79811922, 0.78012266, 0.59494824, 0.44118476],
       [0.08931525, 0.23361348, 0.22063209, 0.13583548],
       [0.07780447, 0.38433094, 0.57551741, 0.61530814]])

In [31]:
np.random.randint(3)

2

In [32]:
np.random.randint(10,20)

15

In [33]:
np.random.randint(1,10,4)

array([1, 8, 7, 2], dtype=int32)

In [34]:
print(np.random.randint(1,10,4))

[5 3 7 2]


In [35]:
m = np.random.randint(10,40,(10,10))
print(m)

[[15 12 30 29 32 10 26 25 25 16]
 [13 22 15 19 21 36 34 31 11 21]
 [10 24 12 32 35 16 33 33 37 35]
 [16 26 32 33 27 36 32 12 25 39]
 [24 14 30 33 35 30 37 13 39 32]
 [22 22 36 39 21 19 23 20 32 13]
 [16 36 26 37 14 10 38 14 36 22]
 [27 22 14 28 21 32 20 18 10 32]
 [26 29 38 21 22 10 23 26 10 25]
 [18 26 32 18 25 37 11 16 36 18]]


In [36]:
m = np.random.randint(1,10,(4,6))
print(m)

[[3 7 7 1 7 1]
 [5 2 8 9 7 8]
 [9 9 5 3 5 8]
 [6 1 6 4 3 3]]


In [37]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [39]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 15, 10, 19],
       [11, 12, 19, 11],
       [15, 19, 19, 15],
       [13, 10, 13, 19],
       [13, 18, 12, 11]], dtype=int32)

In [40]:
type(b)

numpy.ndarray

In [41]:
b

array([[13, 15, 10, 19],
       [11, 12, 19, 11],
       [15, 19, 19, 15],
       [13, 10, 13, 19],
       [13, 18, 12, 11]], dtype=int32)

In [42]:
b[:]

array([[13, 15, 10, 19],
       [11, 12, 19, 11],
       [15, 19, 19, 15],
       [13, 10, 13, 19],
       [13, 18, 12, 11]], dtype=int32)

In [43]:
b[1:3]

array([[11, 12, 19, 11],
       [15, 19, 19, 15]], dtype=int32)

In [44]:
b

array([[13, 15, 10, 19],
       [11, 12, 19, 11],
       [15, 19, 19, 15],
       [13, 10, 13, 19],
       [13, 18, 12, 11]], dtype=int32)

In [45]:
b[1,2]

np.int32(19)

In [46]:
b[1,3]

np.int32(11)

In [47]:
b[1,-1]

np.int32(11)

In [48]:
b

array([[13, 15, 10, 19],
       [11, 12, 19, 11],
       [15, 19, 19, 15],
       [13, 10, 13, 19],
       [13, 18, 12, 11]], dtype=int32)

In [49]:
b[2:3]

array([[15, 19, 19, 15]], dtype=int32)

In [50]:
b[0:-2]

array([[13, 15, 10, 19],
       [11, 12, 19, 11],
       [15, 19, 19, 15]], dtype=int32)

In [51]:
np.random.randint(10,20,(4,4))

array([[13, 16, 15, 15],
       [16, 17, 18, 18],
       [17, 16, 14, 13],
       [19, 10, 19, 15]], dtype=int32)

In [52]:
b

array([[13, 15, 10, 19],
       [11, 12, 19, 11],
       [15, 19, 19, 15],
       [13, 10, 13, 19],
       [13, 18, 12, 11]], dtype=int32)

In [53]:
b[-4,-2]

np.int32(19)

In [54]:
b[-4:2]

array([[11, 12, 19, 11]], dtype=int32)

In [55]:
b[:]

array([[13, 15, 10, 19],
       [11, 12, 19, 11],
       [15, 19, 19, 15],
       [13, 10, 13, 19],
       [13, 18, 12, 11]], dtype=int32)

# Operations

In [56]:
a = np.random.randint(10,20,10)
a

array([19, 10, 19, 16, 16, 13, 12, 10, 16, 19], dtype=int32)

In [57]:
id(a)

1544656826896

In [58]:
arr

array([0, 1, 2, 3, 4, 5])

In [59]:
arr2 = np.random.randint(1,100,(10,10))
arr2

array([[80, 84, 25, 31, 69, 57, 64,  2, 64, 12],
       [14, 68, 45, 31,  2, 26, 52,  4, 63, 89],
       [36, 56, 12, 99, 79, 71, 45, 75, 88, 14],
       [39, 82, 87, 91,  1, 12, 90, 28, 88, 34],
       [49, 46, 83, 84, 95, 98, 56, 49, 34, 82],
       [64, 18, 95, 79, 63, 80,  4, 51, 90,  9],
       [46, 20, 36, 26, 34, 77,  8, 74, 40, 58],
       [50, 17, 52, 17, 36, 24,  2, 69, 51, 98],
       [94, 53, 91, 62, 44, 24, 64, 39, 79, 13],
       [87, 93, 22, 35, 58, 29, 22, 11, 44, 32]], dtype=int32)

In [60]:
arr

array([0, 1, 2, 3, 4, 5])

In [61]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [62]:
arr[:4]

array([0, 1, 2, 3])

In [63]:
arr2[:]

array([[80, 84, 25, 31, 69, 57, 64,  2, 64, 12],
       [14, 68, 45, 31,  2, 26, 52,  4, 63, 89],
       [36, 56, 12, 99, 79, 71, 45, 75, 88, 14],
       [39, 82, 87, 91,  1, 12, 90, 28, 88, 34],
       [49, 46, 83, 84, 95, 98, 56, 49, 34, 82],
       [64, 18, 95, 79, 63, 80,  4, 51, 90,  9],
       [46, 20, 36, 26, 34, 77,  8, 74, 40, 58],
       [50, 17, 52, 17, 36, 24,  2, 69, 51, 98],
       [94, 53, 91, 62, 44, 24, 64, 39, 79, 13],
       [87, 93, 22, 35, 58, 29, 22, 11, 44, 32]], dtype=int32)

In [64]:
arr2[0:5]

array([[80, 84, 25, 31, 69, 57, 64,  2, 64, 12],
       [14, 68, 45, 31,  2, 26, 52,  4, 63, 89],
       [36, 56, 12, 99, 79, 71, 45, 75, 88, 14],
       [39, 82, 87, 91,  1, 12, 90, 28, 88, 34],
       [49, 46, 83, 84, 95, 98, 56, 49, 34, 82]], dtype=int32)

In [65]:
arr2[1,4]

np.int32(2)

In [66]:
arr2[-5,5]

np.int32(80)

In [67]:
arr2[-5,-5]

np.int32(80)

In [68]:
arr2[::-1]

array([[87, 93, 22, 35, 58, 29, 22, 11, 44, 32],
       [94, 53, 91, 62, 44, 24, 64, 39, 79, 13],
       [50, 17, 52, 17, 36, 24,  2, 69, 51, 98],
       [46, 20, 36, 26, 34, 77,  8, 74, 40, 58],
       [64, 18, 95, 79, 63, 80,  4, 51, 90,  9],
       [49, 46, 83, 84, 95, 98, 56, 49, 34, 82],
       [39, 82, 87, 91,  1, 12, 90, 28, 88, 34],
       [36, 56, 12, 99, 79, 71, 45, 75, 88, 14],
       [14, 68, 45, 31,  2, 26, 52,  4, 63, 89],
       [80, 84, 25, 31, 69, 57, 64,  2, 64, 12]], dtype=int32)

In [70]:
arr2

array([[80, 84, 25, 31, 69, 57, 64,  2, 64, 12],
       [14, 68, 45, 31,  2, 26, 52,  4, 63, 89],
       [36, 56, 12, 99, 79, 71, 45, 75, 88, 14],
       [39, 82, 87, 91,  1, 12, 90, 28, 88, 34],
       [49, 46, 83, 84, 95, 98, 56, 49, 34, 82],
       [64, 18, 95, 79, 63, 80,  4, 51, 90,  9],
       [46, 20, 36, 26, 34, 77,  8, 74, 40, 58],
       [50, 17, 52, 17, 36, 24,  2, 69, 51, 98],
       [94, 53, 91, 62, 44, 24, 64, 39, 79, 13],
       [87, 93, 22, 35, 58, 29, 22, 11, 44, 32]], dtype=int32)

In [71]:
arr.max()

np.int64(5)

In [72]:
arr2.max()

np.int32(99)

In [73]:
arr.min()

np.int64(0)

In [74]:
arr2.min()

np.int32(1)

In [75]:
from numpy import*
a=array([1,2,3,4,9])
median(a)

np.float64(3.0)

In [76]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [77]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [78]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [79]:
arr

array([0, 1, 2, 3, 4, 5])

In [80]:
arr.reshape(2,3,order='F') #print element with fortran

array([[0, 2, 4],
       [1, 3, 5]])

In [82]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [83]:
mat = np.arange(0,100).reshape(10,10)

In [84]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [85]:
row=4
col=5

In [86]:
print(row)
print(col)

4
5


In [87]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [88]:
mat[0,1]

np.int64(1)

In [89]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [90]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [91]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [92]:
mat[1:2,2:4]

array([[12, 13]])

# Masking

In [93]:
mat #also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [94]:
id(mat)

1544659494224

In [95]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [96]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [97]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [98]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [99]:
mat[mat==50]

array([50])

In [101]:
a1 = mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [102]:
a2 = mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [104]:
a3 = mat[mat<=50]
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [105]:
a4 = mat[mat==50]
a4

array([50])

In [106]:
print(a1)
print(a2)
print(a3)
print(a4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50]
[50]
